config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => "/cable"

  devise_for :users
  root "rooms#index"

  resources :rooms, only: [:index,:show]

  resources :messages, only: [:create ,:destroy]
  get "/show_additionally"=> "rooms#show_additionally"

  # totalを上に書く
  get "/attends/total" => "attends#total"
  get "/attends/:id/detail" => "attends#detail"
  resources :attends 
  post "/attends/:id/create"=> "attends#create"

  resources :tasks 
  post 'like/:id' => 'likes#create', as: 'create_like'
  delete 'like/:id' => 'likes#destroy', as: 'destroy_like'

  resources :schedules
  post "/schedules/index" => "schedules#create"
  
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :task
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_like
  
  def create
    Like.create!(user_id: current_user.id, task_id: params[:id])
    @tasks_count = current_user.tasks.count.to_f
    @complete = current_user.likes.count.to_f
    @uncomplete = @complete / @tasks_count *100
  end

  def destroy
    Like.find_by(user_id: current_user.id, task_id: params[:id]).destroy
    @tasks_count = current_user.tasks.count.to_f
    @complete = current_user.likes.count.to_f
    @uncomplete = @complete / @tasks_count *100
  end

private
  def set_like
  @task = Task.find(params[:id])
  end

end

app/views/likes/_like.html.erb
<% if current_user.liked_by?(task.id) %>
  <div id="task-<%= task.id %>">
    <div class="card-body task-complete">
      <p class="card-text"><%= l task.created_at, format: '%Y年%-m月%-d日(%a)' %></p>
      <p class="card-text task-title"><%= task
        .title %></p>
      <p class="card-text task-text"><%= simple_format(h(task.content)) %></p>
      <div class="task-btn">
        <%= link_to(destroy_like_path(task), method: "delete", remote: true, class: "btn-warning btn btn-sm") do %>
        <div>解除</div>
        <% end %>
        <%= link_to("/tasks/#{task.id}", method: "delete", class: "btn btn-secondary btn-sm ", data: { confirm: "このタスクを削除しますか？"}) do %>
        <div>削除</div>
        <% end %>
      </div>
    </div>
  </div>
<% else %>
  <div id="task-<%= task.id %>">
    <div class="card-body ">
      <p class="card-text"><%= l task.created_at, format: '%Y年%-m月%-d日(%a)' %></p>
      <p class="card-text task-title"><%= task
        .title %></p>
      <p class="card-text task-text "><%= simple_format(h(task.content)) %></p>
      <div class="task-btn">
        <%= link_to(create_like_path(task), method: "post", remote: true, class: "btn btn-success btn-sm " ) do %>
        <div>完了</div>
        <% end %>
        <%= link_to("/tasks/#{task.id}", method: "delete", class: "btn btn-secondary btn-sm ", data: { confirm: "このタスクを削除しますか？"}) do %>
        <div>削除</div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/likes/_status.html.erb
<p>全タスク <%= @tasks_count.to_i %></p>
<p>完了済み <%= @complete.to_i %></p>
<% if @uncomplete.round(1).nan? == true %>
<p>達成率 0 %</p>
<% else %>
<p>達成率 <%= @uncomplete.round(1) %>%</p>
<% end %>

app/views/likes/create.js.erb
document.getElementById('task-<%= @task.id %>').innerHTML = '<%= j(render 'like', task: @task) %>';
document.getElementById('task-complete').innerHTML= '<%= j(render 'status', tasks_count: @tasks_count, complete: @completes, uncomplete: @uncomplete) %>';

app/views/likes/destroy.js.erb
document.getElementById('task-<%= @task.id %>').innerHTML = '<%= j(render 'like', task: @task) %>';
document.getElementById('task-complete').innerHTML = '<%= j(render 'status',tasks_count: @tasks_count, complete: @complete, uncomplete: @uncomplete) %>';