config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => "/cable"

  devise_for :users
  root "rooms#index"

  resources :rooms, only: [:index,:show]

  resources :messages, only: [:create ,:destroy]
  get "/show_additionally"=> "rooms#show_additionally"

  # totalを上に書く
  get "/attends/total" => "attends#total"
  get "/attends/:id/detail" => "attends#detail"
  resources :attends 
  post "/attends/:id/create"=> "attends#create"

  resources :tasks 
  post 'like/:id' => 'likes#create', as: 'create_like'
  delete 'like/:id' => 'likes#destroy', as: 'destroy_like'

  resources :schedules
  post "/schedules/index" => "schedules#create"
  
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :user
  # validates :content, :title, presence: true, on: :create

  validates :content, presence: true, on: :create
  validates :title, presence: true, on: :create

  validates :content, presence: true, on: :update
  validates :title, presence: true, on: :update

  paginates_per 3
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController

  def index
    @schedules = Schedule.all
    @schedules_show = Schedule.page(params[:page]).order(created_at: :desc)
    @schedule = current_user.schedules.build
  end

  def show
    @schedules = Schedule.all
    @schedule = current_user.schedules.build
    @schedule = Schedule.find_by(id: params[:id])
  end

  def create
    current_user.schedules.create!(schedule_params)
    @schedules = Schedule.all
    redirect_to schedules_path
  end

  def edit
    @schedule = Schedule.find_by(id: params[:id])
  end
  
  def update
    @schedule = Schedule.find_by(id: params[:id])
    Schedule.find(params[:id]).update(schedule_params)
    if @schedule.save
      redirect_to(schedule_path)
    else
      render(schedule_path)
    end
  end

  def destroy
    @schedule = Schedule.find_by(id: params[:id])
    @schedule.destroy
    flash[:alert]= 'スケジュールを削除しました'
    redirect_to schedules_path
  end

private
  def schedule_params
    params.require(:schedule).permit(:id, :title, :content, :user_id, :user_name, :start_time)
  end

end

app/views/schedules/_index.html.erb
<% @schedules_show.each do |schedule| %>
  <%if schedule.created_at > Time.current-12.hour %>
    <%= link_to("/schedules/#{schedule.id}") do %>
    <div class="card sch-card">
      <p class="card-text">
      <span class="new-card">NEW</span><br>
      <%= l schedule.start_time, format: '%Y年%-m月%-d日(%a)%H:%M' %><br>
      <%= schedule.title %>
      </p>
    </div>
    <% end %>
  <%else%>
    <%= link_to("/schedules/#{schedule.id}") do %>
    <div class="card sch-card">
      <p class="card-text">
      <%= l schedule.start_time, format: '%Y年%-m月%-d日(%a)%H:%M' %><br>
      <%= schedule.title %>
      </p>
    </div>
    <% end %>
  <% end %>
<% end %>

app/views/schedules/_modal.html.erb
<!-- スケジュール入力のModal -->
<div class="col-12 tasks">
  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">新規スケジュール</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <%= form_with model: @schedule, local: true do |f| %>
        <div class="modal-body">
          <div class="form-group">
            <%= f.label :タイトル %>
            <%= f.text_field :title, class: "form-control", id: "schedule_title" %>
          </div>
          <div class="form-group">
            <%= f.label :内容 %>
            <%= f.text_area :content, class: "form-control",id: "schedule_content" %>
          </div>
          <div class="form-group">
            <%= f.label :日時 %><br>
            <%= f.datetime_select :start_time,{},class: "form-control sch-time", style: 'display: inline-block;width: auto;'  %>
          </div>
        </div>
        <div class="modal-footer">
          
          <button type="button" class="btn btn-secondary" data-dismiss="modal">閉じる</button>
          <%= f.submit "登録する", class:"btn btn-success", id: 'schedule_button', disabled: 'true' %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<script >
  var scheduleTitle = document.getElementById('schedule_title');
  var scheduleContent = document.getElementById('schedule_content');
  var scheduleButton = document.getElementById('schedule_button');
  
// タイトル、内容の順に入力する想定で、内容入力時に発火するにしている
  scheduleContent.addEventListener("keyup", () => {

    if (scheduleContent.value === '' && scheduleTitle.value === '' ) {

      scheduleButton.disabled = true;

    }else if(scheduleContent.value === '' || scheduleTitle.value === ''){
      scheduleButton.disabled = true;

    }else {

      scheduleButton.disabled = false;
    }
  });
// タイトル、内容の順に入力した後、タイトルだけを消した時にdisableを付与するため記述
  scheduleTitle.addEventListener("keyup", () => {

    if (scheduleContent.value === '' && scheduleTitle.value === '' ) {
      scheduleButton.disabled = true;
  
    }else if(scheduleContent.value === '' || scheduleTitle.value === ''){
      scheduleButton.disabled = true;

    }else {

      scheduleButton.disabled = false;
    }
  });

</script>

app/views/schedules/create.js.erb
<%# ここはjQueryを使用 %>
$("textarea").val("");
$("input").val("");
$('#exampleModal').modal('hide')
$('.tasks').html("<%= escape_javascript(render 'schedules', schedules: @schedules) %>")

app/views/schedules/edit.html.erb
<div class="schedule-wrapper">
  <div class="schedule-header">
    <div class="schedule-edit">
      <h3>スケジュール編集</h3>
      <%= form_with model: @schedule, local: true do |f| %>
        <p><%= f.label "タイトル" %></p>
        <%= f.text_area :title %>
        <p><%= f.label "内容" %></p>
        <%= f.text_area :content %>
        <%= f.submit :編集, class: "btn-warning" %>
      <% end %>
    </div>
  </div>
  <%= link_to "前ページへ",schedules_path %>
</div>

app/views/schedules/index.html.erb
<div class="schedule-wrapper col-12">
  <div class="schedule-header">
    <button type="button" class="btn btn-success w-100 mt-3" data-toggle="modal" data-target="#exampleModal">
      スケジュール作成
    </button>
  </div>

  <div class="schedule-pc">
    <%= month_calendar events: @schedules do |date,schedules| %>
    <%= date.day %>
    <% schedules.each do |schedule| %>
    <div class="schedule-title">
      <%= link_to schedule.title.slice(0..3),"/schedules/#{schedule.id}" %>
    </div>
    <% end %>
    <% end %>
    <div class="sch-display">
      <div id="schedule_list">
        <%= render 'index'%>
      </div>
      <div class="schedule-more">
        <%= link_to_next_page @schedules_show, 'もっと見る', remote: true, id: 'display_more' %>
      </div>
    </div>
  </div>

</div>

<%= render 'modal' %>

app/views/schedules/index.js.erb
<%# jQueryを使用 %>
$('#schedule_list').append("<%= escape_javascript(render 'index', object: @schedules_show) %>");
$("#display_more").replaceWith("<%= escape_javascript( 
link_to_next_page(@schedules_show, 'もっと見る', remote: true, id: 'display_more')) %>");

app/views/schedules/show.html.erb
<div class="schedule-wrapper">
    <div class="schedule-header">
        <div class="card">
            <div class="card-body">
                <p class="card-text">
                    <small>投稿者:
                        <%= @schedule.user.user_name %></small>
                    <br>
                    <small>投稿日:
                        <%= l @schedule.created_at, format: '%Y年%-m月%-d日(%a)%H:%M' %></small>
                    <br>
                    <small>更新日:
                        <%= l @schedule.updated_at, format: '%Y年%-m月%-d日(%a)%H:%M' %></small>
                </p>
                <div class="card-header card-inner">
                    <p class="card-text">
                        日程: <%= l @schedule.start_time, format: '%Y年%-m月%-d日(%a)%H:%M' %>
                    </p>
                </div>
                <div class="card-header card-inner">
                    <p class="card-text">
                        <%= @schedule.title %>
                    </p>
                </div>
                <div class="card-header card-inner">
                    <p class="card-text">
                        <%= simple_format @schedule.content %></p>
                </div>
                <%if @schedule.user.id==current_user.id %>
                <div class="schedule-btn">
                    <button type="button"
                        class="btn sch-btn btn-sm mt-1"><%= link_to("編集",edit_schedule_path)%></button>
                    <button type="button"
                        class="btn sch-del btn-sm mt-1"><%= link_to("削除",schedule_path, method: "delete", data: { confirm: "このスケジュールを削除しますか？"} )%></button>
                </div>
                <%else%>
                <div class="schedule-btn">
                    <button type="button"
                        class="btn sch-btn btn-sm mt-1"><%= link_to("編集",edit_schedule_path)%></button>
                </div>
                <%end%>
            </div>
        </div>
    </div>
</div>