config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => "/cable"

  devise_for :users
  root "rooms#index"

  resources :rooms, only: [:index,:show]

  resources :messages, only: [:create ,:destroy]
  get "/show_additionally"=> "rooms#show_additionally"

  # totalを上に書く
  get "/attends/total" => "attends#total"
  get "/attends/:id/detail" => "attends#detail"
  resources :attends 
  post "/attends/:id/create"=> "attends#create"

  resources :tasks 
  post 'like/:id' => 'likes#create', as: 'create_like'
  delete 'like/:id' => 'likes#destroy', as: 'destroy_like'

  resources :schedules
  post "/schedules/index" => "schedules#create"
  
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  def index
    @users=User.all
    @user= current_user
  end

  def show
    @messages = Message.includes(:user).order(:id).last(10)
    # メッセージ投稿のため
    @message = current_user.messages.build
    end

  def show_additionally
    last_id = params[:oldest_message_id].to_i - 1
    @messages = Message.includes(:user).order(:id).where(id: 1..last_id).last(10)
  end
end

app/views/rooms/_footer.html.erb
<footer class="" id="footer" id="to_bottom">
  <%= form_with model: @message, local: true do |f| %>
  <div class="form-group">
    <!-- ここは自動的に message_content というidが付く。 -->
    <%= f.text_area :content, class: 'form-control', rows: '1', maxlength: '500', id: 'msg_Content'%>
  </div>
  <div class="form-group">
    <div class="dropdown">
      <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown"
        aria-haspopup="true" aria-expanded="false">
        フォトを追加
      </button>
      <div class="dropdown-menu" aria-labelledby="dropdownMenu1">
        <%= f.label :フォト選んでください , class: "pl-3"%><br />
        <%= f.file_field :img, id: "img_name", class: "pl-3" %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= f.submit '送信', class: 'btn btn-primary btn-block', id: 'message-button' ,disabled: 'true' %>
  </div>
  
  <% end %>
</footer>

<script>
  var msgContent = document.getElementById('msg_Content');
  var imgName = document.getElementById('img_name')
  var messageButton = document.getElementById('message-button');
  
// メッセージ入力したら、送信押せるようにする
  msgContent.addEventListener('input', () => {
    if (msgContent.value === '' && imgName.value ==='') {
      messageButton.disabled = true;
    }else if(msgContent.value === '' && imgName.value ===''){
      messageButton.disabled = true;
    } else {
      messageButton.disabled = false;
            // img_name.value ='';        
    }
  });

// 画像選択のみでも、送信押せるようにする
  imgName.addEventListener('input', () => {
    if (msgContent.value === '' && imgName.value ==='') {
      messageButton.disabled = true;
    }else if(msgContent.value === '' && imgName.value ===''){
      messageButton.disabled = true;
    } else {
      messageButton.disabled = false;
      // img_name.value ='';        
    }
  });

// 1MB以上のイメージはアラート出す
  // 制限サイズ
  var sizeLimit = 1024 * 1024 * 1;
  // input要素
  var fileInput = document.getElementById('img_name'); 
  var handleFileSelect = () => {
    var files = fileInput.files;
    for (let i = 0; i < files.length; i++) {
      if (files[i].size > sizeLimit) {
        // ファイルサイズが制限以上
        // エラーメッセージを表示
        alert('ファイルサイズは1MB以下にしてください');
        // inputの中身をリセットし、終了
        fileInput.value = ''; 
        messageButton.disabled = true;
        return; 
      }
    }
  }

  fileInput.addEventListener('change', handleFileSelect);
</script>

app/views/rooms/_header.html.erb
<header class="sticky-top ">
  <nav class="navbar navbar-expand-md navbar-light text-white col-12 rounded">
    <div class="home">
      <%= link_to(rooms_path) do %>
        <span><i class="fas fa-home"></i></span>
      <% end %>
    </div>
    
    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarNav"
      aria-controls="navbarNav" aria-expanded="false" aria-label="ナビゲーションの切替">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to '出席表', "/attends", class: 'navbar-brand nav-link text-white w-100 anime-set fadeIn delay-in' %>
          </li>
          <li class="nav-item active">
            <%= link_to "チャット", "/rooms/#{current_user.id}", class: 'navbar-brand nav-link text-white w-100 anime-set fadeIn delay-in1'%>
          </li>
          <li class="nav-item active">
            <%= link_to "スケジュール",schedules_path ,class: 'navbar-brand nav-link text-white w-100 anime-set fadeIn delay-in2' %>
          </li>
          <li class="nav-item active"><%= link_to "タスク",tasks_path, class: 'navbar-brand nav-link text-white w-100 anime-set fadeIn delay-in3' %>
          </li>

          <li class="nav-item active">
            <%= link_to 'ユーザー編集', edit_user_registration_path, class: 'navbar-brand nav-link text-white w-100 anime-set fadeIn delay-in4' %>
          </li>
          <li class="nav-item active text-white">
            <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'nav-link text-white w-100 anime-set fadeIn delay-in5'%>
          </li>
        <% else %>
          <li class="nav-item active">
            <%= link_to "新規登録", new_user_registration_path, class: 'nav-link text-white w-100' %>
          </li>
          <li class="nav-item active">
            <%= link_to "ログイン", new_user_session_path, class: 'nav-link text-white w-100' %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/rooms/index.html.erb
<div class="users-index">
  <div class="user-image">
    <% if current_user.img? %>
      <img src="<%= current_user.img %>">
    <% else %>
      <%= image_tag asset_path("IMG_3001.jpg") %>
    <% end %>
  </div>
    <h2 style="color:<%=current_user.color%>"><%=@user.user_name%></h2>
  
  <div class="main-menu">
    <ul class="card-group">
      <li class="card close-time">
      <%= link_to(attends_path, id: "attend-btn", method: :post,data: { confirm: "出席しますか？" }) do %>
        <span><i class="fas fa-user-check icon-size"></i></span>
        出席
      </li>
      <% end %>
      <li class="card">
        <%= link_to("/rooms/#{current_user.id}") do %>
        <span><i class="far fa-comments icon-size"></i></span>
        チャット
      </li>
      <% end %>
      <li class="card">
        <%= link_to(schedules_path) do %>
        <span><i class="far fa-calendar-alt icon-size"></i></span>
        スケジュール
      </li>
      <% end %>
      <li class="card">
        <%= link_to(tasks_path) do %>
        <span><i class="fas fa-tasks icon-size"></i></span>
        タスク
      </li>
      <% end %>
      <li class="card">
        <%= link_to("/attends") do %>
        <span><i class="fas fa-graduation-cap icon-size"></i></span>
        出席表
      </li>
      <% end %>
    </ul>
  </div>
</div>
</div>

<% if @user.id == 1 %>
<% @users.each do |user| %>
<% if user.user_name==nil %>
  <div class="users-list shadow" style="background-color:<%=user.color%>">
    <p><%= user.id%>.<%= user.user_name%><a>NO NAME</a></p>
    <p><%= user.email%></p>
  </div>
<%else%>
  <div class="users-list shadow" style="background-color:<%=user.color%>">
    <p><%= user.id%>.<%= user.user_name%></p>
    <p><%= user.email%></p>
  </div>
<%end%>
<%end%>
<%end%>

<script>
// 営業時間外は出席ボタンを押せないようにする
    var currentTime = new Date().getHours();
    var closeTime = document.getElementsByClassName('close-time');
    var attendBtn = document.getElementById('attend-btn')
// 営業時間外にページがロードされた時の処理
// AM0:00からAM8:59は出席できない
window.addEventListener('load',()=>{
    if (0 <= currentTime && currentTime <= 8){
      closeTime[0].classList.add('closed-hours');
      attendBtn.disabled = true;
    }
});
// 営業時間外に出席ボタンを押した時の処理
    attendBtn.addEventListener('click',()=>{
    if (0 <= currentTime && currentTime <= 8){
      alert('営業時間外です')
      closeTime[0].classList.add('closed-hours');
      attendBtn.disabled = true;
    }
});

</script>

app/views/rooms/show.html.erb
<div class="message-wrapper">
  <div id="message-container">
    <%= render @messages %>
  </div>
  <%= render 'footer' %>
</div>

app/views/rooms/show_additionally.js.erb
var messageHeight = messageContainer.scrollHeight
messageContainer.insertAdjacentHTML('afterbegin', "<%= j(render @messages) %>")
var newMessageHeight = messageContainer.scrollHeight
window.scrollBy(0, newMessageHeight - messageHeight)

<%# メッセージの読み込み %>
<% if @messages.present? %>
showAdditionally = true
<% end %>